spring.application.name=forum

server.port=${APP_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:forum_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}

spring.security.filter.dispatcher-types=REQUEST

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:Gtl1o/+JE/XbbaOr1tyBF/TOtBBSwWALP6GyhBK76s63dVYIaVk2zUXiDLihUdD0oaSBmANhe+JHRlmafNcM1Q==}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}